package com.bank.islamic.takafulpolicyadministration;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Takaful Policy Administration
 *
 * Business Area:      Takaful and Shared Operations
 * Business Domain:    Takaful
 * Functional Pattern: Administer
 * Asset Type:         Takaful Certificate
 * Control Record:     Takaful Certificate Administrative Plan
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Takaful Policy Administration — BIAN Semantic API")
                .description("Service Domain 'Takaful Policy Administration' (Administer pattern) "
                        + "operating on the 'Takaful Certificate Administrative Plan' control record.")
                .version("0.1.0"));
    }
}
